name: Build Release

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test

  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: $(npm bin)/standard-version --color=always | awk '! /Run.+to publish/'
      - run: git push --follow-tags origin master  
